### ISSUE TITLE
miniProxy does not seem to be effective

### ISSUE THREAD

**Issue by daiaji** [joshdick/miniProxy#89] opened 2017-10-05 14:05 UTC
http://www.dlsite.com/home/work/=/product_id/RJ203903.html
![default](https://user-images.githubusercontent.com/25875791/31231312-15636408-aa19-11e7-98fa-3294730295f3.png)
Some of the links are not being proxied

**Comment by BenNottelling** [comment] 2017-10-05 16:25
miniProxy doesn't handle dynamic links if I'm not mistaken

**Comment by joshdick** [comment] 2017-10-05 16:31
Correct; closing as duplicate of #56

**Comment by joshdick** [comment] 2017-10-05 16:31
Duplicate of #56.

**Closed by joshdick** 2017-10-05 16:31 UTC

**Comment by daiaji** [comment] 2017-10-05 17:35
@joshdick @BenNottelling 😢
Is the problem on the PHP?

**Comment by BenNottelling** [comment] 2017-10-05 17:42
The problem is from scripts loading links in after the page loads (like JavaScript) because miniProxy will only proxify all of the links once, but then more load in. I think I'm right
