### ISSUE TITLE
Failed to load resource 404

### ISSUE THREAD

**Issue by haniag** [joshdick/miniProxy#81] opened 2017-08-08 13:03 UTC
I am getting a lot of "Failed to load resource: the server responded with a status of 404 (Not Found)" error messages in Chrome console. The site in example is pandora.com, where js files are being called with an incorrect URL destination like:

http://[proxy ip]/web-version/0.36.0/smartconversion-index-js.a9b95df0fad31976a7f1.js

which should be: 

http://[proxy ip]/proxy.php?https://www.pandora.com/web-version/0.36.0/smartconversion-index-js.a9b95df0fad31976a7f1.js

This causes the site not to load. Is this a bug or limitation? Do I need to changed anything in proxy/server settings?

**Comment by joshdick** [comment] 2017-08-08 18:39
Possibly a duplicate of #56?

**Comment by haniag** [comment] 2017-08-15 07:52
maybe, as I am not sure. However, I just want to make sure that there aren't any changes to be made for apache, etc.. as I also noticed that bbc and instagram sites also don't display.

**Closed** 2020-04-27 01:27 UTC
Labels: closed-when-deprecated
