### ISSUE TITLE
Is there a way to obscure the URL

### ISSUE THREAD

**Issue by drvladb** [joshdick/miniProxy#126] opened 2019-03-25 13:09 UTC
https://x/y/minipxy.php?http://example.com/
Is there a potential way to obscure the ?http://example.com/ part
Maybe use POST and Not GET?

**Comment by joshdick** [comment] 2019-03-26 12:39
Thanks for the suggestion. I'm closing this issue since it's a duplicate of #122 .

**Closed by joshdick** 2019-03-26 12:39 UTC
