### ISSUE TITLE
Visiting google.com takes user to different locale

### ISSUE THREAD

**Issue by sulliops** [joshdick/miniProxy#97] opened 2017-12-05 23:20 UTC
When I put "google.com" in the text box and click go, it leads me to the Brazilian version of google (google.com.br). When I try on another proxy, it takes me to another random locale (but not English).

Can this be fixed or is it Google's issue?

**Comment by joshdick** [comment] 2017-12-06 00:09
I cannot reproduce this behavior.

This is most likely because Google is trying to geolocate based on the IP address of the machine running the proxy, so if you're getting redirected to the Brazilian version of Google, it's probably because miniProxy itself is running on a machine that's physically located there. The same is likely true for the other proxy you tried.

Based on this, I'm going to close this issue, but if I was wrong, feel free to continue the dialog here!

**Closed by joshdick** 2017-12-06 00:09 UTC

**Comment by BenNottelling** [comment] 2017-12-06 00:24
If you set anonymize to false your true ip will be sent which may correct the location, but it will also lower your privacy and will no longer hide your IP address

**Comment by sulliops** [comment] 2017-12-06 00:33
@BenNottelling that didn't seem to do anything. I believe @joshdick's response is correct.
