### ISSUE TITLE
Add support for twitch.tv?

### ISSUE THREAD

**Issue by GGrandma** [joshdick/miniProxy#98] opened 2017-12-06 16:49 UTC
Whenever visiting twitch.tv an error shows up saying “Failed to load module”

**Comment by joshdick** [comment] 2018-01-01 20:50
This is just a guess, but it looks like this happens because the page attempts to load assets dynamically via JavaScript which bypasses the proxy (see #56), and then loading fails due to [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) violations because the proxied page doesn't match the location that the dynamically-loaded assets are served from.

Closing as a duplicate of #56.

**Closed by joshdick** 2018-01-01 20:50 UTC
