### ISSUE TITLE
Netflix WebSockets ( Willing to Pay For Help)

### ISSUE THREAD

**Issue by bionichuman** [joshdick/miniProxy#115] opened 2018-08-27 11:15 UTC
Netflix does not seem to work due to web sockets. Can someone add web sockets so you  could watch netflix through this? I would be willing to pay for your hard work.

**Comment by joshdick** [comment] 2018-11-23 00:08
Closing this as a duplicate of #114.

Thanks for offering to pay, but miniProxy is just a spare-time project for me. 🙂

**Closed by joshdick** 2018-11-23 00:08 UTC
